#!/usr/bin/env bash

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create a default HTML page
echo "Hello World!" > /var/www/html/index.html

# starting nginx
sudo service nginx start
