#!/usr/bin/env bash
# install and run nginx server.

sudo apt-get update

sudo apt-get install -y nginx

sudo chown -R ubuntu /var/www

echo "Hello World" > /var/www/html/index.nginx-debian.html

sudo service nginx start
