#!/usr/bin/env bash
# Update package lists

apt-get update

apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

service nginx restart

echo "Hello World!" > /var/www/html/index.html
