#!/usr/bin/env bash

set -e

if ! nginx -v > /dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
    }
}"

if ! grep -q "sketchfab.com/bluepeno/models" /etc/nginx/sites-enabled/default; then
    echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
fi

if ! systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
else
    sudo systemctl restart nginx
fi
