#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer.

# Exit immediately if a command exits with a non-zero status.
set -e

# Check if HAProxy is installed, install if not
if ! command -v haproxy &> /dev/null; then
    echo "HAProxy not found, installing..."
    sudo apt-get update
    sudo apt-get install -y haproxy
else
    echo "HAProxy is already installed."
fi

echo -e "\nPreparing configuration...\n"

# Backup the existing HAProxy configuration file for safety
echo "Backing up the default HAProxy configuration file."
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_default.backup

# Define the new HAProxy configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 421599-web-01 54.84.246.55:80 check
    server 421599-web-02 52.91.154.11:82 check
"

# Apply the new configuration
echo "Applying new HAProxy configuration."
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Ensure HAProxy is enabled to start at boot
echo "Enabling HAProxy to start on boot."
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "Configuration applied - Round-robin load balancing configured for web-01 and web-02."

# Start or restart HAProxy to apply the new configuration
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    echo "Starting HAProxy..."
    sudo service haproxy start
else
    echo "Restarting HAProxy..."
    sudo service haproxy restart
fi

echo "HAProxy setup complete."
