#!/usr/bin/env bash
# This script installs and configures HAProxy on a Ubuntu machine to load balance traffic between two web servers

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start at boot
sudo systemctl enable haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 421599-web-01 54.84.246.32:80 check
    server 421599-web-02 52.91.154.11:80 check
EOF

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Display HAProxy status
sudo systemctl status haproxy
