#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and mimics service status

service nginx stop
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
nginx -s reload
