#!/usr/bin/env bash
#6. Write a shell script that prints numbers from 1 to 20. And for multiples of ‘4’ print “bad luck from China”, for multiples of ‘9’ print “bad luck from Japan” and for multiples of ‘17’ print “bad luck from Italy”.

count=1

while [ $count -le 20 ]
do
    case $count in
        4)
            echo $count
            echo "bad luck from China"
            ;;
        9)
            echo $count
            echo "bad luck from Japan"
            ;;
        17)
            echo $count
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac

    count=$((count+1))
done
