#!/bin/bash
# This script will print out the minutes of each hour from 1 to 59 for each hour from 0 to 11

hour=0

while [ $hour -lt 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]
    do
        echo $minute
        minute=$((minute+1))
    done
    hour=$((hour+1))
done
