#!/usr/bin/env bash
# This script will print out the minutes of each hour from 1 to 59 for each hour from 0 to 11

hour=0

while [ $hour -lt 12 ]; do
    printf -v padded_hour "%02d" $hour
    echo "Hour: $padded_hour"
    
    minute=0
    while [ $minute -lt 59 ]; do
        printf -v padded_minute "%02d" $minute
        echo $padded_minute
        minute=$((minute+1))
    done
    
    hour=$((hour+1))
done
