#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
if ! id "nginx" &>/dev/null; then useradd -r -s /bin/false nginx; fi
systemctl restart nginx
